BEGIN TRANSACTION;

CREATE TABLE [User] (
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	SecondName NVARCHAR(50) NOT NULL
);

CREATE TABLE Category (
	Id INT IDENTITY PRIMARY KEY,
	Description NVARCHAR(255) NOT NULL,
);

CREATE TABLE Project (
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL, 
	Description NVARCHAR(255) NOT NULL,
	CreationDate DATE NOT NULL DEFAULT GETDATE(),
	CreatorId INT NOT NULL,
	CategoryId INT NOT NULL,
	FOREIGN KEY (CreatorId) REFERENCES [User](Id),
	FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);

CREATE TABLE Comment (
	Id INT IDENTITY PRIMARY KEY,
	Text NVARCHAR(255) NOT NULL,
	Date DATE NOT NULL DEFAULT GETDATE(),
	UserId INT NOT NULL,
	ProjectId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (ProjectId) REFERENCES Project(Id)
);

CREATE TABLE Vote (
	Id INT IDENTITY PRIMARY KEY,
	UserId INT NOT NULL,
	ProjectId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (ProjectId) REFERENCES Project(Id)
);

COMMIT TRANSACTION;